### PR TITLE
Solved Style/RegexpLiteral offenses 

### LINKED ISSUE #133: Solve Style/RegexpLiteral offenses
There is at least one offenses for Style/RegexpLiteral Rubocop cop, as you can see in [.rubocop_todo.yml](https://github.com/openSUSE/trollolo/blob/master/.rubocop_todo.yml).

Solve the offense. This cop support autocorrection, but the offense can not be automatically corrected.

### PR DESCRIPTION
**Pull request by namangupta01**
Closes #133

### CODE REVIEW

**Comment by Ana06** [comment]
@namangupta01 what is the state of this?

**Comment by namangupta01** [comment]
@Ana06 Sorry, for the late reply! I am having exams going on so didn't get the time to reply. I will update the pr soon.

**Comment by Ana06** [comment]
@namangupta01 If you are busy and don't have time you can consider closing this PR and allow someone else to work on this issue. :wink:

**Comment by namangupta01** [comment]
@Ana06 I will keep this in mind ! Although i have updated the pr.

**Pull request merged**
