### PR TITLE
implement some Burndown-as-a-service

### PR DESCRIPTION
**Pull request by bmwiedemann**
rspec tests are missing
and automatic-new-sprint functionality still needs to be designed and implemented

### CODE REVIEW

**Comment by cornelius** [comment]
Do you intend to add some tests?

**Comment by bmwiedemann** [comment]
Tests for get-board-list should be easy with mocking, but I don't have experience in this yet (and not much time atm).

**Comment by bmwiedemann** [comment]
rebased, need help fixing get-board-list tests

**Comment by Ana06** [comment]
@bmwiedemann @cornelius what is the state of that? It is already 2 years and a half since it was open. Are there plans to finish it or can we close it? :confused:

**Comment by Ana06** [comment]
I guess I can close this. If I am wrong, please just reopen it. :smile:

**Pull request closed without merging**
