### PR TITLE
Swimlanes

### PR DESCRIPTION
**Pull request by cornelius**
Add support for swimlanes. See the README for documentation.

### CODE REVIEW

**Comment by cornelius** [comment]
When I do releases I use `yes_ship_it`. That also provides an option to collect the info for the changelog from the git commit logs. That's easier than trying to continuously keeping track by editing the file all the time.

I do have fixed Rubocop in the meantime. Would be nice, if Rubocop would run locally as part of the tests as well so that you don't have to wait for CI to see when something is going wrong.

**Comment by Ana06** [comment]
@cornelius 

> When I do releases I use yes_ship_it. That also provides an option to collect the info for the changelog from the git commit logs. That's easier than trying to continuously keeping track by editing the file all the time.

But I guess it needs some modifications even with `yes_ship_it`, because many commits do not need to be in the CHANGELOG. You only edit the file when adding a new feature. I find it much easier to write a feature when you implement it than when you release. But if you don't agree we should remove the _Master (unreleased)_ part of the [CHANGELOG](https://github.com/openSUSE/trollolo/blob/master/CHANGELOG.md).

> I do have fixed Rubocop in the meantime. Would be nice, if Rubocop would run locally as part of the tests as well so that you don't have to wait for CI to see when something is going wrong.

Rubocop can be run locally, it is documented in the [CONTRIBUTING GUIDE](https://github.com/openSUSE/trollolo/blob/master/CONTRIBUTING.md#to-run-rubocop). Or do you mean something different?

**Comment by cornelius** [comment]
Yes, the commit log messages have to be edited. I usually generate a raw changelog from the commit messages (yes_ship_it) has a simple command to help with that, and then I edit that into a form which can be put into the CHANGELOG.md. The advantage of this is that nothing is missed, no matter if people remember to edit the CHANGELOG.md together with the code implementing something new. I actually don't think we have to decide for one method or the other. Finalizing the CHANGELOG for the release is a manual process in any case and we can use the input from both what already is there and what is in the git logs.

Rubocop can be run locally by explicitly calling it, but it would be nice if there would be one command to run all tests which can be used locally but also on travis so that it's easier to replicate what the CI is doing. This could be a rake call or somehow be put into rspec or maybe an extra script. For my personal workflow it would be most convenient to have an rspec call without arguments run all tests which are also run by travis.

**Comment by Ana06** [comment]
@cornelius 

> Yes, the commit log messages have to be edited. I usually generate a raw changelog from the commit messages (yes_ship_it) has a simple command to help with that, and then I edit that into a form which can be put into the CHANGELOG.md. The advantage of this is that nothing is missed, no matter if people remember to edit the CHANGELOG.md together with the code implementing something new. I actually don't think we have to decide for one method or the other. Finalizing the CHANGELOG for the release is a manual process in any case and we can use the input from both what already is there and what is in the git logs.

I'll remove this section then.

> Rubocop can be run locally by explicitly calling it, but it would be nice if there would be one command to run all tests which can be used locally but also on travis so that it's easier to replicate what the CI is doing. This could be a rake call or somehow be put into rspec or maybe an extra script. For my personal workflow it would be most convenient to have an rspec call without arguments run all tests which are also run by travis.

I'll create an issue for a rake task 👍

**Comment by cornelius** [comment]
@Ana06 I don't think anything is missing. I'll squash the branch when merging. If you want to make GitHub happy you can approve the PR so that GitHub doesn't say anymore "Review required".

**Comment by cornelius** [comment]
Squashed and merged.

**Pull request closed without merging**
